# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cloudless
email: info@cloudless.com
description: >- # this means to ignore newlines until "baseurl:"
  Cloudless is a tool to abstract away many of the details that make working
  with the cloud slow, frustrating, and error prone.  It aims to do the right
  thing that is transparent to users, yet still be powerful and flexible enough
  that no one has to rearchitect their system to use it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://getcloudless.com" # the base hostname & protocol for your site, e.g. http://example.com
docs_url: "https://docs.getcloudless.com"
github_username:  "getcloudless/cloudless"
logo: "/assets/images/cloudless-logo-nobackground.svg"
copyright: ""

# Build settings
markdown: kramdown
remote_theme: "mmistakes/jekyll-theme-basically-basic"
#plugins:
#- jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - deployment
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
